name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:         # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping Streamlit app
        run: |
          URLS=(
            "https://venkateshbalu.streamlit.app/"   # ✅ your live app
          )
          for URL in "${URLS[@]}"; do
            echo "Pinging $URL..."
            curl -fLsS --max-time 20 \
              -A "streamlit-keepalive/1.0" \
              "${URL}?keepalive=$(date +%s)" \
              >/dev/null
          done
