name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes UTC
  workflow_dispatch:

concurrency:
  group: keep-streamlit-awake
  cancel-in-progress: true

jobs:
  wake:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install --with-deps chromium

      - name: Wake only if sleeping
        env:
          APP_URL: "https://venkateshbalu.streamlit.app/?keepalive=${{ github.run_id }}"
        run: |
          node - <<'NODE'
          const { chromium } = require('playwright');

          (async () => {
            const browser = await chromium.launch({
              args: ['--no-sandbox', '--disable-dev-shm-usage']
            });
            const page = await browser.newPage();

            // "Implicit-like" global waits
            page.setDefaultTimeout(30000);            // all actions
            page.setDefaultNavigationTimeout(90000);  // navigations

            // 1) Open app
            await page.goto(process.env.APP_URL, { waitUntil: 'domcontentloaded' });

            // 2) Helpers (strict: only true when real app is rendered)
            const isAwake = async () =>
              (await page.locator('div[data-testid="stAppViewContainer"], div.stApp').count()) > 0;

            // 3) Already awake?
            if (await isAwake()) {
              console.log('✅ App already awake. Nothing to do.');
              await browser.close(); process.exit(0);
            }

            // 4) Selenium-like "implicit wait" for the wake button
            const wakeBtn = page.locator('button[data-testid="wakeup-button-viewer"]');

            // Wait up to 60s for the button to be visible; if not, just exit softly
            try {
              await wakeBtn.waitFor({ state: 'visible', timeout: 60000 });
              console.log('💤 Wake button visible. Clicking…');
              // Locator click already auto-waits for stability; force just in case
              await wakeBtn.click({ force: true, timeout: 20000 });
            } catch {
              console.log('ℹ️ Wake button not found/visible within timeout; app may be booting already.');
              await browser.close(); process.exit(0);
            }

            // 5) Give the app time to boot, then poll for Streamlit container
            try { await page.waitForLoadState('networkidle', { timeout: 60000 }); } catch {}
            const deadline = Date.now() + 120000; // up to 2 minutes total
            while (Date.now() < deadline && !(await isAwake())) {
              await page.waitForTimeout(1500);
            }

            if (await isAwake()) {
              console.log('🚀 App woke successfully.');
            } else {
              console.log('⚠️ Clicked but app not fully ready yet; will retry next run.');
            }

            await browser.close(); process.exit(0);
          })().catch(e => { console.error(e?.stack || e); process.exit(1); });
          NODE
