name: Keep Streamlit Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes UTC
  workflow_dispatch:

concurrency:
  group: keep-streamlit-awake
  cancel-in-progress: true

jobs:
  wake:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Faster browser install & system deps
      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
        with:
          version: 1.47.2
          # Browsers default to all; limit to chromium for speed
          with-deps: true
      - run: npm init -y && npm i playwright@1.47.2

      - name: Wake only if sleeping
        env:
          APP_URL: "https://venkateshbalu.streamlit.app/?keepalive=${{ github.run_id }}"
        run: |
          node - <<'NODE'
          const { chromium } = require('playwright');

          (async () => {
            const browser = await chromium.launch(); // headless by default
            const page = await browser.newPage();
            page.setDefaultTimeout(30000);

            await page.goto(process.env.APP_URL, { waitUntil: 'domcontentloaded', timeout: 60000 });

            async function isAwake() {
              return (await page.locator('div[data-testid="stAppViewContainer"], div.stApp').count()) > 0;
            }

            // Already up?
            if (await isAwake()) {
              console.log('App already awake. Nothing to do.');
              await browser.close();
              process.exit(0);
            }

            // Try exact wake button first
            let clicked = false;
            const exact = page.locator('button:has-text("Yes, get this app back up!")').first();
            if (await exact.count()) {
              console.log('Sleeping screen detected. Clicking exact wake button.');
              await exact.click().catch(()=>{});
              clicked = true;
            } else {
              // Fallback regex options
              const patterns = [/wake up/i, /wake/i, /start app/i, /start/i, /resume/i, /launch/i, /run app/i];
              for (const re of patterns) {
                const btn = page.getByRole('button', { name: re }).first();
                if (await btn.count()) {
                  console.log('Sleeping screen detected. Clicking:', re);
                  await btn.click().catch(()=>{});
                  clicked = true;
                  break;
                }
              }
            }

            if (!clicked) {
              console.log('No wake button found; app may be starting or in transient state.');
              await browser.close();
              process.exit(0);
            }

            // Wait for Streamlit to come up (max ~2 minutes)
            const deadline = Date.now() + 120000;
            while (Date.now() < deadline && !(await isAwake())) {
              await page.waitForTimeout(1500);
            }

            if (await isAwake()) {
              console.log('App woke successfully.');
            } else {
              console.log('Wake clicked, but app not ready yet—will try next run.');
            }

            await browser.close();
            process.exit(0); // soft-success either way
          })().catch(e => { console.error(e?.stack || e); process.exit(1); });
          NODE
